package com.omneAgate.wholeSaler.DTO;

import java.io.Serializable;

import lombok.Data;

/**
 * This class is used to transfer device details.
 *
 * @author user1
 */
@Data
public class DeviceDto implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private long id;            // Autogenerated device id

    private long FPSId;    // Unique FPS id

    private String SIM;            //SIM Card number associated with the device

    private String deviceId;    //Device IMEI id

    private boolean active;

    private String deviceNumber;


}
